### ISSUE TITLE
What does "stateless" mean?

### ISSUE THREAD

**Issue by emilva** [cloudchefs/docker-defect-dojo#4]
Hi, thanks for building this docker setup! Only one I found that actually works on first attempt 👍 

Quick question: What do you mean by `"stateless"`, I see you have a mysql configured in the docker-compose file.

**Comment by abelmokadem** [comment]
Thanks for using our docker setup! :grin: 

Maybe it's not the right wording, but from what I remember the original defect dojo docker image has a DB inside the container. With the one we built, you can run as many defect dojo containers and point them all to the same DB endpoint. You can bring them down and bring new ones up without any problem. Thus, there is no "state" in the container.

The example that I have created contains a mysql container to show how you can connect to a mysql DB without having to run one on your local machine. We are actually running this container and connecting it to an AWS RDS instance.

**Comment by emilva** [comment]
Thanks for the explanation! Sounds like a good approach to scaling it :)
